### ISSUE TITLE
📌 Configure Staging: dev and prod

### ISSUE THREAD

**Issue by dev-ujin** [beerlot/beerlot-server#69]
# Acceptance Criteria
- [x] Create a GCP project for prod
- [x] Configure GitHub environment for prod
- [x] Hide secret informations

# Issues
- #31
